baseURL = "/"
disqusShortname = ""
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
paginate = 3
theme = "anubis"
title = "pranav goyanka's webpage"
date = true
[author]
name = "Pranav Goyanka"
[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 3
[[menu.main]]
identifier = "archive"
name = "blog"
url = "/posts/"
weight = 1
[[menu.main]]
identifier = "category"
name = "categories"
url = "/categories/"
weight = 2
[params]
author = "Pranav Goyanka"
description = "Pranav Goyanka's home on the Interwebs"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
