baseURL = "https://pranavgoyanka.netlify.app/"
languageCode = "en-us"
title = "pranav goyanka's webpage"
theme = "anubis"
paginate = 3

enableRobotsTXT = true

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Pranav Goyanka"

[params]
   author = "Pranav Goyanka"
   description = "Pranav Goyanka's home on the Interwebs"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "blog"
    identifier = "archive"
    url = "/posts/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
series = "series"