# baseURL = "https://old.pranavgoyanka.me/"
baseURL = "https://pranavgoyanka.me/"
disqusShortname = ""
enableRobotsTXT = true
languageCode = "en-us"
paginate = 3
theme = "anubis"
title = "pranav goyanka's webpage"
date = true
[author]
name = "Pranav Goyanka"
# [[menu.main]]
# identifier = "about"
# name = "about"
# url = "/about/"
# weight = 3
[[menu.main]]
identifier = "archive"
name = "blog"
url = "/posts/"
weight = 1
# [[menu.main]]
# identifier = "work"
# name = "work"
# url = "/work/"
# weight = 2
[[menu.main]]
identifier = "resume"
name = "resume"
url = "/resume"
# url = "/Pranav_Goyanka_Resume.pdf"
weight = 3
[[menu.main]]
identifier = "contact"
name = "contact"
url = "/contact"
weight = 4
# [[menu.main]]
# identifier = "category"
# name = "categories"
# url = "/categories/"
# weight = 3
# [[menu.main]]
# identifier = "about"
# name = "about"
# url = "/about/"
# weight = 4
[params]
author = "Pranav Goyanka"
description = "Pranav Goyanka's home on the Interwebs"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
